#!/bin/sh
set -e

case "$1" in
  configure|triggered)
    if command -v glib-compile-schemas >/dev/null 2>&1; then
      glib-compile-schemas /usr/share/glib-2.0/schemas || true
    fi
  ;;
esac

exit 0

